[db]
host="127.0.0.1"
username="root"
password="123456"
port="3306"
charset="utf8mb4"
dbName="write_score"

[http]
path=""
port="8099"

[redis]
host="127.0.0.1"
port="6379"
password=""
db=0

[qiniuyun]
Zone="storage.ZoneHuadong"
Bucket="ljxyzwd"
AccessKey="s1rWDFSf50yO6qPvzsUiAXWUnmT5cJo7js4zfBqv"
SecretKey="2cEL7ggvSRJrCQSq_YHQQXzT-fTQXv8ew8Gmf-8a"
Domain="stzljlqgn.hn-bkt.clouddn.com"
